<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Gdb on Dilawar's Blog</title><link>http://localhost:1313/tags/gdb/</link><description>Recent content in Gdb on localhost:1313</description><generator>Hugo -- gohugo.io</generator><language>en-us</language><copyright>© 2021, Dilawar Singh</copyright><lastBuildDate>Tue, 03 Nov 2020 00:00:00 +0000</lastBuildDate><atom:link href="http://localhost:1313/tags/gdb/index.xml" rel="self" type="application/rss+xml"/><item><title>Debugging python extension in gdb</title><link>http://localhost:1313/posts/2020/2020-11-03-debugging-python-extension-in-gdb/</link><pubDate>Tue, 03 Nov 2020 00:00:00 +0000</pubDate><guid>http://localhost:1313/posts/2020/2020-11-03-debugging-python-extension-in-gdb/</guid><description>
$ gdb -ex r --args python myscript.py If you are using virtual environment then you are likely to run into the following error. …</description></item></channel></rss>